using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AlbionRadaro
{
    public enum HarvestableType
    {
        WOOD,
        WOOD_GIANTTREE,
        WOOD_CRITTER_GREEN,
        WOOD_CRITTER_RED,
        WOOD_CRITTER_DEAD,
        WOOD_GUARDIAN_RED,
        ROCK,
        ROCK_CRITTER_GREEN,
        ROCK_CRITTER_RED,
        ROCK_CRITTER_DEAD,
        ROCK_GUARDIAN_RED,
        FIBER,
        FIBER_CRITTER,
        FIBER_GUARDIAN_RED,
        FIBER_GUARDIAN_DEAD,
        HIDE,
        HIDE_FOREST,
        HIDE_STEPPE,
        HIDE_SWAMP,
        HIDE_MOUNTAIN,
        HIDE_HIGHLAND,
        HIDE_CRITTER,
        HIDE_GUARDIAN,
        ORE,
        ORE_CRITTER_GREEN,
        ORE_CRITTER_RED,
        ORE_CRITTER_DEAD,
        ORE_GUARDIAN_RED,
        DEADRAT,
        SILVERCOINS_NODE,
        SILVERCOINS_LOOT_STANDARD_TRASH,
        SILVERCOINS_LOOT_VETERAN_TRASH,
        SILVERCOINS_LOOT_ELITE_TRASH,
        SILVERCOINS_LOOT_ROAMING,
        SILVERCOINS_LOOT_ROAMING_MINIBOSS,
        SILVERCOINS_LOOT_ROAMING_BOSS,
        SILVERCOINS_LOOT_STANDARD,
        SILVERCOINS_LOOT_VETERAN,
        SILVERCOINS_LOOT_ELITE,
        SILVERCOINS_LOOT_STANDARD_MINIBOSS,
        SILVERCOINS_LOOT_VETERAN_MINIBOSS,
        SILVERCOINS_LOOT_ELITE_MINIBOSS,
        SILVERCOINS_LOOT_STANDARD_BOSS,
        SILVERCOINS_LOOT_VETERAN_BOSS,
        SILVERCOINS_LOOT_ELITE_BOSS,
        SILVERCOINS_LOOT_CHEST_STANDARD,
        SILVERCOINS_LOOT_CHEST_STANDARD_TRASH,
        SILVERCOINS_LOOT_CHEST_VETERAN,
        SILVERCOINS_LOOT_CHEST_DEMON,
        CHEST_EXP_SILVERCOINS_LOOT_STANDARD,
        CHEST_EXP_SILVERCOINS_LOOT_VETERAN,
        SILVERCOINS_LOOT_SARCOPHAGUS_STANDARD_MINIBOSS,
    }
    public enum HarvestableMobType
    {
        ESSENCE,
        SWAMP,
        STEPPE,
        MOUNTAIN,
        FOREST,
        HIGHLAND

    }
}
